module.exports = {
  arrowParens: "always",
  bracketSpacing: true,
  embeddedLanguageFormatting: "auto",
  endOfLine: "lf",
  filepath: undefined,
  htmlWhitespaceSensitivity: "css",
  insertPragma: false,
  jsxBracketSameLine: false,
  jsxSingleQuote: false,
  parser: undefined,
  printWidth: 100,
  proseWrap: "preserve",
  quoteProps: "as-needed",
  rangeEnd: Infinity,
  requirePragma: false,
  semi: true,
  singleQuote: false,
  tabWidth: 4,
  trailingComma: "es5",
  useTabs: false,
  vueIndentScriptAndStyle: false,
};
